### ISSUE TITLE
VPT Performance on VTAB-1K

### ISSUE THREAD

**Issue by Zenvi** [ChengHan111/VPT-or-FT#1]
Hi, thank you very much for your work and sharing!

I'm just confused about the performance of VPT in your paper:
In Table 1 of your paper, you obtained the following results:
| Dataset    | CIFAR100 | Caltech101 | DTD  | Flowers102 | Pets | SVHN | Sun397 | Mean  |
|------------|----------|------------|------|------------|------|------|--------|-------|
| Accuracy   | 77.7 | 90.2 | 68.8 | 98.1 | 88.4 | 82.5 | 51.0 | 79.53 |

Which was significantly higher than the results reported in the original VPT paper:

| Dataset    | CIFAR100 | Caltech101 | DTD  | Flowers102 | Pets | SVHN | Sun397 | Mean  |
|------------|----------|------------|------|------------|------|------|--------|-------|
| Accuracy   | 77.7     | 86.9       | 62.6 | 97.5       | 87.3 | 74.5 | 51.2   | 76.81 |

I assume that you are using VPT shallow as in your appendix, Table 16-18, you reported the prompt length, which is identical to the prompt length reported in original VPT paper about VPT-SHALLOW.

In this repo, you mentioned that you are using the hyperparameters released by the original VPT repo.

So, since you are using the same prompt length and same hyperparameters as original VPT, why is your performance so better than the original VPT?

**Comment by ChengHan111** [comment]
Hi, thank you for your interest in our paper! That is a really good question. We reran and reported the results for 5 runs for this results. We found that VPT has significantly higher performance than the original report version. So we calibrated them accordingly.  You can try to rerun the results as well since the seeds are fixed values. Thank you!

**Comment by Zenvi** [comment]
The hyperparameters are exactly the same as in the csv file released in VPT repo?

**Comment by ChengHan111** [comment]
Yes they are. Thank you!

**Comment by MosyMosy** [comment]
Can you please share the hyperparameters files again? The original links for hyperparameters and the prepared dataset are dead.
